//! Assembles the instruction lists generated by gen_isa.py with this assembler,
//! at comptime and at runtime, and compares them with sjasmplus and, for the
//! documented forms, with z88dk z80asm.

const std = @import("std");
const z80 = @import("z80asm");

const source = @embedFile("out/isa_cases.asm");
const reference = @embedFile("out/isa_cases.bin");
const documented = @embedFile("out/isa_documented.asm");
const z88dk = @embedFile("out/isa_documented.z88dk.bin");

var workspace: z80.Workspace(0x10000, 64, 16) = undefined;

fn expectSame(what: []const u8, want: []const u8, got: []const u8) !void {
    if (std.mem.eql(u8, want, got)) return;
    const n = @min(want.len, got.len);
    const at = for (0..n) |i| {
        if (want[i] != got[i]) break i;
    } else n;
    std.debug.print("{s}: {d} bytes, reference {d}; first difference at offset {d}\n", .{ what, got.len, want.len, at });
    return error.TestExpectedEqual;
}

fn runtime(text: []const u8) ![]const u8 {
    const r = z80.assemble(text, .{}, workspace.buffers());
    for (r.diagnostics) |d| std.debug.print("{f}\n", .{d});
    try std.testing.expect(r.ok());
    return r.bytes;
}

test "runtime assembly matches sjasmplus" {
    try expectSame("runtime vs sjasmplus", reference, try runtime(source));
}

test "comptime assembly matches sjasmplus" {
    try expectSame("comptime vs sjasmplus", reference, comptime z80.comptimeAssemble(source, .{}));
}

test "documented forms match z88dk z80asm in both modes" {
    try expectSame("runtime vs z88dk z80asm", z88dk, try runtime(documented));
    try expectSame("comptime vs z88dk z80asm", z88dk, comptime z80.comptimeAssemble(documented, .{}));
}
