//! Assembles the instruction list generated by gen_isa.py with this assembler,
//! at comptime and at runtime, and compares both with sjasmplus.

const std = @import("std");
const z80 = @import("z80asm");

const source = @embedFile("out/isa_cases.asm");
const reference = @embedFile("out/isa_cases.bin");

var workspace: z80.Workspace(0x10000, 64, 16) = undefined;

fn expectSame(mode: []const u8, got: []const u8) !void {
    if (std.mem.eql(u8, reference, got)) return;
    const n = @min(reference.len, got.len);
    const at = for (0..n) |i| {
        if (reference[i] != got[i]) break i;
    } else n;
    std.debug.print("{s}: {d} bytes, sjasmplus {d}; first difference at offset {d}\n", .{ mode, got.len, reference.len, at });
    return error.TestExpectedEqual;
}

test "runtime assembly matches sjasmplus" {
    const r = z80.assemble(source, .{}, workspace.buffers());
    for (r.diagnostics) |d| std.debug.print("{f}\n", .{d});
    try std.testing.expect(r.ok());
    try expectSame("runtime", r.bytes);
}

test "comptime assembly matches sjasmplus" {
    try expectSame("comptime", comptime z80.comptimeAssemble(source, .{}));
}
